title: Scattered thoughts
description: Miscellaneous observations on how the world works
url: "https://daninge.github.io"
baseurl: "/scatteredthoughts"

markdown: kramdown
permalink: /:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

